FROM node:14 as build

WORKDIR /app
COPY package.json package-lock.json ./
RUN --mount=type=secret,id=npmrc,dst=./.npmrc npm ci
COPY . .
RUN npm run build-prod

FROM nginx:1.21-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/project/ /usr/share/nginx/html
